# Generated by Django 4.2.3 on 2023-08-22 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import product_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('price', models.IntegerField(verbose_name='price')),
                ('short_description', models.CharField(db_index=True, max_length=360, null=True, verbose_name='description')),
                ('description', models.TextField(db_index=True, null=True, verbose_name='main description')),
                ('is_active', models.BooleanField(default=False, null=True, verbose_name='active/inactive')),
                ('is_delete', models.BooleanField(null=True, verbose_name='deleted')),
                ('image', models.ImageField(blank=True, null=True, upload_to=product_app.models.url_upload_image_product, verbose_name='image')),
                ('date_register', models.DateField(verbose_name='date of add product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='title')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('is_delete', models.BooleanField(null=True, verbose_name='حذف شده / حذف نشده')),
            ],
        ),
        migrations.CreateModel(
            name='RatingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('ip', models.GenericIPAddressField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_app.product')),
            ],
        ),
    ]
