# Generated by Django 4.2.3 on 2023-08-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_ratingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingproduct',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ratingproduct',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ratingproduct',
            name='comment',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
