# Generated by Django 4.2.3 on 2023-08-22 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('no_paid', 'پرداخت نشده'), ('canceled', 'لغو شده'), ('pending_payment', ' در انتظار پرداخت'), ('paid', ' پرداخت شده')], max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='date of payment')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.IntegerField(blank=True, null=True, verbose_name='final_price')),
                ('count', models.IntegerField(verbose_name='count')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('color', models.CharField(max_length=150)),
            ],
        ),
    ]
