# Generated by Django 4.2.3 on 2023-08-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('no_paid', 'پرداخت نشده'), ('canceled', 'لغو شده'), ('pending_payment', ' در انتظار پرداخت'), ('paid', ' پرداخت شده')], max_length=20),
        ),
    ]
